package nl.thijsmolendijk.PGMXMLValidator.bukkit;


/**
 * Represents a type of potion and its effect on an entity.
 */
public enum PotionEffectType {
   SPEED, SLOW, FAST_DIGGING, SLOW_DIGGING, INCREASE_DAMAGE, HEAL, HARM, JUMP, CONFUSION, REGENERATION, DAMAGE_RESISTANCE, FIRE_RESISTANCE, WATER_BREATHING, INVISIBILITY, BLINDNESS, NIGHT_VISION, HUNGER, 
   WEAKNESS, POSION, WITHER, HEALTH_BOOST, ABSORBTION, SATURATION;
}